name: Application CI

on:
  push:
    paths:
      - 'application-service/**'
      - 'patient-service/**'
      - 'order-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      #   Configure Docker for Artifact Registry 
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # -------- Application Service --------
      - name: Build & Push Application Service
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/application-service:latest ./application-service
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/application-service:latest

      # -------- Patient Service --------
      - name: Build & Push Patient Service
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/patient-service:latest ./patient-service
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/patient-service:latest

      # -------- Order Service --------
      - name: Build & Push Order Service
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/order-service:latest ./order-service
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hackathon-repo/order-service:latest
